### ISSUE TITLE
ERROR : Assembly-CSharp already is deobfuscated!

### ISSUE THREAD

**Issue by Markezzz** [DerPopo/deobfuscate-7dtd#1]
Hey people,

i use the last relase of the Deobfuscate-7dtd and if i drag and drop the Assembly-CSharp.dll from alloc to the Deobfuscate-Main.exe it shows this message: ERROR : Assembly-CSharp already is deobfuscated!

What do i wrong? :/

Greets,
Markezzz

**Comment by Alloc86** [comment]
The message is actually quite precise: You try to run the deobfuscator on a DLL that already is deobfuscated so it won't be able to do any more deobfuscation. You need to pass it an obfuscated DLL instead.

**Comment by Markezzz** [comment]
But which file i have to use from your site on https://7dtd.illy.bz/wiki/Server%20fixes ?

You say in your wiki this: The Assembly-CSharp.dll is first deobfuscated with the ​Deobfuscator. Then the 7dtd-server-fixes.dll can be build referencing this assembly. At last the deobfuscated Assembly-CSharp.dll is patched with the ​Assembly-Patcher so it calls the new methods in the 7dtd-server-fixes.dll.

Thats why I'm confused. :D

**Comment by Alloc86** [comment]
Just use the one from your game. That's the only obfuscated one.

**Comment by 0x900x90** [comment]
Don't know how to contact you another way.

Your Unity Assets Bundle Extractor project is not working on Windows XP. You using com-object to create fileopen dialog. This com exist only from Windows Vista. Can you, please, fix this?

**Comment by DerPopo** [comment]
I've added a fallback to XP's file dialog. I couldn't test it on XP but it should work.

**Comment by 0x900x90** [comment]
I've not tested all functionality, but fileopen dialog works fine now.

I used VirtualBox + LiveCD Windows7 before. Now i can use it without VM's.

Thank you.
