### ISSUE TITLE
ERROR : There are no patches to apply (patchers.xml doesn't exist)! Exiting.

### ISSUE THREAD

**Issue by JoeDM09** [DerPopo/deobfuscate-7dtd#2]
I have compiled with VS 2013 and installed the Mono.Cecil NuGet packages. I am attempting to deobfuscate the Assembly-CSharp.dll from the standard release, not the Dedicated Server release if that has any relationship?

As indicated the patchers.xml does not exist. How would this be generated?

I have rebuilt the entire solution and the patchers folder included a number of dll's however no xml's

**Comment by Alloc86** [comment]
You have to create it manually or use the one from the release package as a template. We should really include that in the source though ... ;)

**Comment by JoeDM09** [comment]
Sorry if this is an uneducated question, I've been unable to locate any XML files in the repo to use as a template and to be honest I'm not in the know regarding deobfuscation and don't know what the patchers.xml should contain.

**Comment by JoeDM09** [comment]
Mostly, I just want to be able to get the server fixes compiled with the standard release of 7D2D as the dedicated server release does not appear on the list of dedicated servers, beyond that I would like to be able to contribute to the modding society.

**Comment by Alloc86** [comment]
As I said you have to download a release package.
If you look at the projects main page on the top there is a link called ["releases"](https://github.com/DerPopo/deobfuscate-7dtd/releases) and there you get the release which includes the XML.

What OS do you run? The Dedi build definitely shows up on Steam's Tools section unless you are on MacOS.

**Comment by JoeDM09** [comment]
Running Windows, I have installed the Dedi build from steam tools and can manually join the server however the server does not show in the list of public servers inside of the game. This is using the same config files and ports as the standard build which does show up in the public game list.

**Comment by Alloc86** [comment]
Shouldn't happen as the code is basically the same. If you want to debug that further we should move this conversation to the forum or a private channel, you can find my contact information [here](http://christian.illy.bz/)

**Comment by JoeDM09** [comment]
Thanks Alloc86, you've been a great help. I got the patcher loaded and working.
