### ISSUE TITLE
Multiple Errors and an Exception

### ISSUE THREAD

**Issue by JoeDM09** [DerPopo/deobfuscate-7dtd#3]
I have been trying to resolve issues with the assembly-patcher and it looks like this may seed from a failed or partial deobfuscated file.

I have tried deobfuscating directly from the release and from the built source however both receive the same errors:

---

ERROR : (Command_listents.Help()): MethodDefinition not found!
ERROR : (Command_listents.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_listplayers.Help()): MethodDefinition not found!
ERROR : (Command_listplayers.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_listthreads.Help()): MethodDefinition not found!
ERROR : (Command_listthreads.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_enablescope.Help()): MethodDefinition not found!
ERROR : (Command_enablescope.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_chunkcache.Help()): MethodDefinition not found!
ERROR : (Command_chunkcache.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_showchunkdata.Help()): MethodDefinition not found!
ERROR : (Command_showchunkdata.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_gameover.Help()): MethodDefinition not found!
ERROR : (Command_gameover.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_debugmenu.Help()): MethodDefinition not found!
ERROR : (Command_debugmenu.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_creativemenu.Help()): MethodDefinition not found!
ERROR : (Command_creativemenu.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_shutdown.Help()): MethodDefinition not found!
ERROR : (Command_shutdown.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_spawnentity.Help()): MethodDefinition not found!
ERROR : (Command_spawnentity.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_settime.Help()): MethodDefinition not found!
ERROR : (Command_settime.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_setgamepref.Help()): MethodDefinition not found!
ERROR : (Command_setgamepref.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_kick.Help()): MethodDefinition not found!
ERROR : (Command_kick.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_ban.Help()): MethodDefinition not found!
ERROR : (Command_ban.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_admin.Help()): MethodDefinition not found!
ERROR : (Command_admin.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_mod.Help()): MethodDefinition not found!
ERROR : (Command_mod.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_whitelist.Help()): MethodDefinition not found!
ERROR : (Command_whitelist.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_cp.Help()): MethodDefinition not found!
ERROR : (Command_cp.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_say.Help()): MethodDefinition not found!
ERROR : (Command_say.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_convertdtm.Help()): MethodDefinition not found!
ERROR : (Command_convertdtm.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_mem.Help()): MethodDefinition not found!
ERROR : (Command_mem.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_aiddebug.Help()): MethodDefinition not found!
ERROR : (Command_aiddebug.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_spawnwanderinghorde.Help()): MethodDefinition not found!
ERROR : (Command_spawnwanderinghorde.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_spawnairdrop.Help()): MethodDefinition not found!
ERROR : (Command_spawnairdrop.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_spawnsupplycrate.Help()): MethodDefinition not found!
ERROR : (Command_spawnsupplycrate.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_shownexthordetime.Help()): MethodDefinition not found!
ERROR : (Command_shownexthordetime.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_sounddebug.Help()): MethodDefinition not found!
ERROR : (Command_sounddebug.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_smoothworld.Help()): MethodDefinition not found!
ERROR : (Command_smoothworld.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_generatemap.Help()): MethodDefinition not found!
ERROR : (Command_generatemap.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_saveworld.Help()): MethodDefinition not found!
ERROR : (Command_saveworld.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_buff.Help()): MethodDefinition not found!
ERROR : (Command_buff.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_debuff.Help()): MethodDefinition not found!
ERROR : (Command_debuff.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_starve.Help()): MethodDefinition not found!
ERROR : (Command_starve.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_thirsty.Help()): MethodDefinition not found!
ERROR : (Command_thirsty.RepeatInterval()): MethodDefinition not found!
ERROR : (Command_convertof.Help()): MethodDefinition not found!
ERROR : (Command_convertof.RepeatInterval()): MethodDefinition not found!
INFO : Successful: 142 / Failed: 72

---

WARNING : Unable to find NetPackage_EntityTeleport.Read! (already defined in a base class?)
WARNING : Unable to find NetPackage_EntityTeleport.Write! (already defined in a base class?)
WARNING : Unable to find NetPackage_PlayerDisconnect.Read! (already defined in a base class?)
WARNING : Unable to find NetPackage_PlayerDisconnect.Write! (already defined in a base class?)
WARNING : Unable to find NetPackage_PlayerDisconnect.GetEstimatedPackageSize! (already defined in a base class?)

---

ERROR : ERROR : Invoking the Patch method for PacketOrNotRelatedStuffPatcher resulted in an exception :
ERROR : Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UMA, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at NetworkPatcher.Helpers.PatchSubMethods(MethodDefinition method, String newName) in h:\Programming\742d\deobfuscate-7dtd-master\deobfuscate-7dtd-master\NetworkPatcher\Helpers.cs:line 47
   at NetworkPatcher.Helpers.PatchVMethod(MethodDefinition method, String newName) in h:\Programming\742d\deobfuscate-7dtd-master\deobfuscate-7dtd-master\NetworkPatcher\Helpers.cs:line 84
   at NetworkPatcher.PatchPackageQueue.Patch(Logger logger, AssemblyDefinition asmCSharp) in h:\Programming\742d\deobfuscate-7dtd-master\deobfuscate-7dtd-master\NetworkPatcher\PatchPackageQueue.cs:line 106
   at NetworkPatcher.NetworkPatcher.Patch(Logger logger, AssemblyDefinition asmCSharp, AssemblyDefinition __reserved) in h:\Programming\742d\deobfuscate-7dtd-master\deobfuscate-7dtd-master\NetworkPatcher\NetworkPatcher.cs:line 158

---

![2015-02-08 00_17_59-h__programming_742d_deobfuscate-7dtd-master_deobfuscate-7dtd-master_bin_debug_de](https://cloud.githubusercontent.com/assets/10508890/6092382/0e69f0a2-af28-11e4-82ea-9ae5385ba454.png)
![2015-02-08 00_18_12-h__programming_742d_deobfuscate-7dtd-master_deobfuscate-7dtd-master_bin_debug_de](https://cloud.githubusercontent.com/assets/10508890/6092383/0e6beb28-af28-11e4-8199-ca2055b7c83e.png)

**Comment by Alloc86** [comment]
The first parts are normal (some descendent classes just don't overwrite (-> reimplement) the given methods). E.g. the 72 failed ones in the ManualDeobfuscator part are correct for the current game release.

The other one is because you didn't copy a dependency of the DLL to the folder in which you ran the Deobfuscator / AC#.dll is in. In this case you'd have to copy UMA.dll but I suggest simply copying all DLLs or running the deobfuscator directly in the managed folder.

**Comment by JoeDM09** [comment]
Thanks Alloc86, I had discovered the dependency UMA.dll was missing however taking your advise I have copied all managed .dll files.
Looking much better.
